name: hybrid_sailmate
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  mapbox_gl: ^0.9.0
  geolocator: ^6.1.4
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.0.0
  firebase_core: 0.4.5
  firebase_analytics: ^5.0.2
  flutter_hooks: 0.14.1
  colorful_safe_area: ^0.2.1
  fontisto_flutter: ^3.0.4
  google_fonts: ^1.1.1
  easy_localization: ^2.3.3
  shared_preferences: 0.5.12+4
  amplify_core: <1.0.0
  amplify_auth_cognito: <1.0.0
  flutter_svg: ^0.19.0
  pin_code_fields: ^6.0.1
  config_repository:
    path: packages/config_repository
  point_of_interest_repository:
    path: packages/point_of_interest_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
