name: config_repository
description: Dart package which manages the configuration domain.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  firebase_core: 0.4.5
  firebase_remote_config: ^0.3.1+1
